### ISSUE TITLE
Error when running bundle exec rake db:create:all

### ISSUE THREAD

**Issue by JamieMason** [andrew/github-inbox#34]
Hi, 
While following the setup steps on the README, I ran `bundle exec rake db:create:all` on my laptop and got the following error.

```
foldleft at jmason in ~/Development/github-inbox on master
$ bundle exec rake db:create:all
Created database 'github-inbox_development'
Created database 'github-inbox_test'
FATAL:  role "github-inbox" does not exist
Couldn't create database for {"adapter"=>"postgresql", "encoding"=>"unicode", "pool"=>5, "database"=>"github-inbox_production", "username"=>"github-inbox", "password"=>nil}
rake aborted!
ActiveRecord::NoDatabaseError: FATAL:  role "github-inbox" does not exist
/Users/foldleft/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/foldleft/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
PG::ConnectionBad: FATAL:  role "github-inbox" does not exist
/Users/foldleft/.rbenv/versions/2.3.3/bin/bundle:22:in `load'
/Users/foldleft/.rbenv/versions/2.3.3/bin/bundle:22:in `<main>'
Tasks: TOP => db:create:all
(See full trace by running task with --trace)
```

> “...fine to continue with the rest of the instructions, there's no need for the production db on your laptop”
> – https://twitter.com/teabass/status/810501534136074240

This issue is to update the README to explain that this error is ok to ignore. I would do this myself by pull request but I don't have knowledge of postgres unfortunately.

Thanks for this great tool, really excited to try it out.

**Comment by karpiu** [comment]
Typical Postgresql+Rails error. Solution:

Run in `psql` console the following sql:

`CREATE ROLE "github-inbox" LOGIN SUPERUSER;`
