### ISSUE TITLE
Allow "unarchiving" of notifications

### ISSUE THREAD

**Issue by andrew** [andrew/github-inbox#6]
Currently you can't pull a notification out of the archive from the Web UI, you should be able to revert the archiving action in case you need to put it back in the inbox

**Comment by GiacomoLaw** [comment]
https://github.com/andrew/github-inbox/commit/5fbfe7f73fcb6cdb32b5cc8c5919bc1938aec8f1

Is this implemented? :)

**Comment by andrew** [comment]
Yep
